superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/')),
    

]

superhero_project/superheroes/urls.py
from django.urls import path

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('delete/<int:hero_id>', views.delete, name= 'delete'),
    path('update/<int:hero_id>', views.update, name='update')

]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero


# Create your views here.

def index(request):
    all_heroes = Superhero.objects.all()
    context = { 
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }        
    return render(request, 'superheroes/detail.html', context)


def create(request):
    if request.method == "POST":
        
        name= request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary= request.POST.get('primary')
        secondary= request.POST.get('secondary')
        catchpharse= request.POST.get('catchphrase')
        new_hero= Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchpharse)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))

    else:    
        return render(request, 'superheroes/create.html')



def update(request, hero_id):
    new_hero=Superhero.objects.filter(id=hero_id)    
    
    name= new_hero.update('new_hero.name')
    alter_ego = new_hero.update('new-hero.alter_ego')
    primary= new_hero.update('new_hero.primary')
    secondary= new_hero.update('new_hero.secondary')
    catchpharse= new_hero.update('new_hero.catchphrase')
    new_hero=Superhero(name=name, alter_ego=alter_ego, primary=primary,secondary=secondary,catchpharse=catchpharse)
    new_hero.save()
    return HttpResponseRedirect(reverse('superheroes:index'))
    
   

        
        
        

def delete(request, hero_id):
    single_hero = Superhero.objects.filter(id=hero_id)
    single_hero.delete()
    return HttpResponseRedirect(reverse('superheroes:index'))        

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action= "{% url 'superheroes:create' %}" method="post">
        {%csrf_token %}
        Name: <input type="text" name="name" id="name"> <br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"> <br />
        Primary Ability: <input type="text" name="primary" id="primary"> <br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"> <br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"> <br />
        <input type="submit" value="Add!">

    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Superhero Details </title>
    </head>
    <body>
        <h1>Hero details</h1>
        <ul>
            <li> <h2>Super Hero Name</h3></li>
            <ul> <h3>{{single_hero.name}}</h2> </ul>
            <li> <h2>Alter Ego</h3></li>
            <ul> <h3>{{single_hero.alter_ego}}</h3> </ul>
            <li> <h2>Super Hero Primary Ability</h3></li>
            <ul> <h3>{{single_hero.primary_ability}}</h3> </ul>
            <li> <h2>Super Hero Secondary ability</h3></li>
            <ul> <h3>{{single_hero.secondary_ability}}</h3> </ul>
            <li> <h2>Catch Phrase</h3></li>
            <ul> <h3>{{single_hero.catch_phrase}}</h3> </ul>
            <a href="{% url 'superheroes:index'%}">Return to Index</a>
            <a href="{% url 'superheroes:delete' single_hero.id %}"> Delete Hero</a>
            
            
            
        </ul>
    </body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Superhero Index</title>
    </head>
    <body>
        <h1>List of Heroes</h1>
        <ul>
            {% for hero in all_heroes %}
            <li> <h2>{{hero.name}}</h2> <a href="{% url 'superheroes:detail' hero.id %}"> Hero's details</a> <br> <a href="{% url 'superheroes:update' hero.id %}">Update Hero</a></li>
            {% endfor %}
        </ul>
        <a href="{% url 'superheroes:create' %}">Add New Hero</a> 
    </body>
</html>

superhero_project/superheroes/templates/superheroes/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Update Heroe Here</h1>
        <form action= "{% url 'superheroes:update' hero.id %}" method="post">
        {%csrf_token %}

        Name: <input type="text" name="name" id="name"> <br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"> <br />
        Primary Ability: <input type="text" name="primary" id="primary"> <br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"> <br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"> <br />
        <input type="submit" value="Add!">

    </form>

    
</body>
</html>